### ISSUE TITLE
The method 'map' was called on null. Receiver: null Tried calling: map<SymptomCard>(Closure: (SymptomCard) => SymptomCard)

### ISSUE THREAD

**Issue by shahharoon** [godfreycomputing/cardwidget#1]
The method 'map' was called on null.
Receiver: null
Tried calling: map<SymptomCard>(Closure: (SymptomCard) => SymptomCard)

**Comment by shahharoon** [comment]
noSuchMethodError: The method 'map' was called on null

**Comment by godfreycomputing** [comment]
This was already discussed in Facebook.  The list needs to be filled with whatever card you need.
